Repository mkqavi/commit-email, pull requests merged in 2021-11, with the labels that each got.

#7 Setup test, clippy and format workflow
  .github/workflows/ci.yml
Labels: enhancement

#23 Remove remaining clippy warnings
  src/config.rs
  src/main.rs
  src/repo.rs
Labels: enhancement

#27 Add shell script to readme
  README.md
Labels: documentation

#8 Define exit keys and improve readme and user messages
  README.md
  src/main.rs
Labels: enhancement

#29 Update default branch name to main
  .github/workflows/ci.yml
Labels: bug
